services:
  - type: web
    name: absensi-pegawai
    env: python
    buildCommand: "pip install -r functions/requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker functions.app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        value: <your-database-url>
      - key: SECRET_KEY
        value: <your-secret-key>